### ISSUE TITLE
隐藏滚动条

### ISSUE THREAD

**Issue by SandBoat** [SandBoat/knowledge#4]
-  通过溢出隐藏滚动条（支持大部分浏览器）

``` css
.outer {
  width: 100px;
  height: 100px;
}

.inner {
  width: 120px;
  height: 100%;
  overflow-x: hidden; // 内部元素宽度超出隐藏
  overflow-y: auto;
  height: 200px;
}
```

- Chrome
``` css
*::-webkit-scrollbar {
  display: none;
}
```

![属性兼容情况](https://user-images.githubusercontent.com/13296146/76606057-90d4b380-654c-11ea-9387-68c3175aabb3.jpg)

- Firefox (仅兼容 Firefox version >= 64)
``` css
* {
  scrollbar-width: none;
}
```
